#!/bin/bash

system_type=$(uname -s)
distro_type=$(uname -r)
windows_user=$(/mnt/c/Windows/System32/cmd.exe /c 'echo %USERNAME%' | sed -e 's/\r//g')

[[ $distro_type == *WSL2 ]] && yadm config local.class wsl2
[[ $distro_type == *Microsoft ]] && yadm config local.class wsl1

sudo apt update && \
sudo apt install zsh git zip unzip fzf -y

sudo apt-get install --reinstall ca-certificates

if ! command -v brew >/dev/null 2>&1; then
    NONINTERACTIVE=1
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    sudo apt-get install build-essential -y
fi

if ! command -v mvn >/dev/null 2>&1; then
    TMP_MAVEN_VERSION=3.9.2
    wget https://apache.org/dist/maven/maven-3/$TMP_MAVEN_VERSION/binaries/apache-maven-$TMP_MAVEN_VERSION-bin.tar.gz -P /tmp
    sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt
    sudo rm /tmp/apache-maven-*-bin.tar.gz
    sudo ln -s /opt/apache-maven-$TMP_MAVEN_VERSION /opt/maven
fi

if ! command -v sdk >/dev/null 2>&1; then
    curl -s "https://get.sdkman.io" | bash
fi

if ! command -v kubectl >/dev/null 2>&1; then
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm ~/kubectl
fi

if ! command -v helm >/dev/null 2>&1; then
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
fi

if ! command -v kubectx >/dev/null 2>&1; then
    sudo git clone https://github.com/ahmetb/kubectx /opt/kubectx
    sudo ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
    sudo ln -s /opt/kubectx/kubens /usr/local/bin/kubens

    mkdir -p ~/.completions
    ln -s /opt/kubectx/completion/_kubectx.zsh ~/.completions/_kubectx.zsh
    ln -s /opt/kubectx/completion/_kubens.zsh ~/.completions/_kubens.zsh
fi

if ! command -v docker >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | sh
fi

[[ $(docker version) =~ "The command 'docker' could not be found in this WSL 1 distro." ]] && curl -fsSL https://get.docker.com | sh

if ! command -v gcloud >/dev/null 2>&1; then
    sudo apt-get install apt-transport-https ca-certificates gnupg -y
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    sudo apt-get update && sudo apt-get install google-cloud-cli -y
fi

if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
fi

if [ ! -f "$HOME/.tmux/plugins/tpm" ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [ ! -f "$HOME/.dircolors" ]; then
    curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output ~/.dircolors
fi

if [ ! -f "$HOME/.kube/config" ]; then
    mkdir -p $HOME/.kube
    cp /mnt/c/Users/$windows_user/.kube/config $HOME/.kube/config
    chmod go-r ~/.kube/config
fi

echo "================================================================"
echo "First open a new shell then you can run the following:"
echo "To install Java run 'sdk install java 20-amzn'"
echo "To install NodeJs run 'nvm install 18.16.0'"

